# version: '3'
# services:

#   video-streaming:
#     image: video-streaming
#     build: 
#       context: ./video-streaming
#       dockerfile: Dockerfile
#     container_name: video-streaming
#     ports:
#      - "4000:80"
#     environment:
#       - PORT=80
#     restart: "no"

version: '3'

services:

  # Video streaming service replicas
  video-streaming1:
    image: video-streaming
    build:
      context: ./video-streaming
      dockerfile: Dockerfile
    container_name: video-streaming1
    ports:
     - "3001:3001"
    environment:
      - PORT=3001
    restart: "no"

  video-streaming2:
    image: video-streaming
    build:
      context: ./video-streaming
      dockerfile: Dockerfile
    container_name: video-streaming2
    ports:
     - "3002:3002"
    environment:
      - PORT=3002
    restart: "no"

  video-streaming3:
    image: video-streaming
    build:
      context: ./video-streaming
      dockerfile: Dockerfile
    container_name: video-streaming3
    ports:
     - "3003:3003"
    environment:
      - PORT=3003
    restart: "no"

  # NGINX reverse proxy and load balancer
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"    # HTTP port (for redirection)
      - "443:443"  # HTTPS port
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl  # Mount SSL certificates
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Mount NGINX configuration
    depends_on:
      - video-streaming1
      - video-streaming2
      - video-streaming3
    restart: "always"
